// apps/main-app/src/implementations/react/TodoListExample.tsx
import { useState } from 'react';

export function TodoListExample() {
  const [title, setTitle] = useState('');
  const [items, setItems] = useState(['Описать сценарий']);

  return (
    <form
      onSubmit={(event) => {
        event.preventDefault();
        if (!title.trim()) return;
        setItems([...items, title]);
        setTitle('');
      }}
    >
      <input value={title} onChange={(event) => setTitle(event.target.value)} />
      <button>Добавить</button>
      <ul>
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </form>
  );
}

// apps/main-app/src/implementations/vue/TodoListExample.vue
<script setup lang="ts">
import { ref } from 'vue';

const title = ref('');
const items = ref(['Описать сценарий']);

function addItem() {
  if (!title.value.trim()) return;
  items.value.push(title.value);
  title.value = '';
}
</script>

<template>
  <form @submit.prevent="addItem">
    <input v-model="title" />
    <button>Добавить</button>
    <ul>
      <li v-for="item in items" :key="item">{{ item }}</li>
    </ul>
  </form>
</template>
